ValueSet: OPNSVS
Id: OP-NS-VS
Description: "Valueset of national identity card's namespaces"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^title = "Standard namespaces for national identity card"
* ^version = "1.0.0"
* ^status = #draft
* ^experimental = false
* ^date = "2023-01-01"
* ^publisher = "HL7 Czech Republic"
* ^language = #cs
//* ^jurisdiction = urn:iso:std:iso:3166#CZ "Czechia"
* insert SetFmmandStatusRule(1, draft)

* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-AFG "Pas: Afghanistan"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-ALB "Pas: Albania"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-DZA "Pas: Algeria"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-ASM "Pas: American Samoa"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-AND "Pas: Andorra"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-AGO "Pas: Angola"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-AIA "Pas: Anguilla"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-ATA "Pas: Antarctica"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-ATG "Pas: Antigua and Barbuda"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-ARG "Pas: Argentina"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-ARM "Pas: Armenia"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-ABW "Pas: Aruba"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-AUS "Pas: Australia"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-AUT "Pas: Austria"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-AZE "Pas: Azerbaijan"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-BHS "Pas: Bahamas (the)"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-BHR "Pas: Bahrain"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-BGD "Pas: Bangladesh"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-BRB "Pas: Barbados"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-BLR "Pas: Belarus"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-BEL "Pas: Belgium"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-BLZ "Pas: Belize"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-BEN "Pas: Benin"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-BMU "Pas: Bermuda"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-BTN "Pas: Bhutan"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-BOL "Pas: Bolivia (Plurinational State of)"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-BES "Pas: Bonaire, Sint Eustatius and Saba"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-BIH "Pas: Bosnia and Herzegovina"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-BWA "Pas: Botswana"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-BVT "Pas: Bouvet Island"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-BRA "Pas: Brazil"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-IOT "Pas: British Indian Ocean Territory (the)"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-BRN "Pas: Brunei Darussalam"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-BGR "Pas: Bulgaria"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-BFA "Pas: Burkina Faso"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-BDI "Pas: Burundi"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-CPV "Pas: Cabo Verde"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-KHM "Pas: Cambodia"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-CMR "Pas: Cameroon"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-CAN "Pas: Canada"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-CYM "Pas: Cayman Islands (the)"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-CAF "Pas: Central African Republic (the)"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-TCD "Pas: Chad"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-CHL "Pas: Chile"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-CHN "Pas: China"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-CXR "Pas: Christmas Island"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-CCK "Pas: Cocos (Keeling) Islands (the)"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-COL "Pas: Colombia"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-COM "Pas: Comoros (the)"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-COD "Pas: Congo (the Democratic Republic of the)"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-COG "Pas: Congo (the)"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-COK "Pas: Cook Islands (the)"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-CRI "Pas: Costa Rica"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-HRV "Pas: Croatia"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-CUB "Pas: Cuba"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-CUW "Pas: Curaçao"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-CYP "Pas: Cyprus"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-CZE "Pas: Czechia"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-CIV "Pas: Côte d'Ivoire"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-DNK "Pas: Denmark"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-DJI "Pas: Djibouti"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-DMA "Pas: Dominica"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-DOM "Pas: Dominican Republic (the)"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-ECU "Pas: Ecuador"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-EGY "Pas: Egypt"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-SLV "Pas: El Salvador"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-GNQ "Pas: Equatorial Guinea"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-ERI "Pas: Eritrea"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-EST "Pas: Estonia"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-SWZ "Pas: Eswatini"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-ETH "Pas: Ethiopia"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-FLK "Pas: Falkland Islands (the) [Malvinas]"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-FRO "Pas: Faroe Islands (the)"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-FJI "Pas: Fiji"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-FIN "Pas: Finland"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-FRA "Pas: France"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-GUF "Pas: French Guiana"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-PYF "Pas: French Polynesia"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-ATF "Pas: French Southern Territories (the)"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-GAB "Pas: Gabon"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-GMB "Pas: Gambia (the)"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-GEO "Pas: Georgia"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-DEU "Pas: Germany"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-GHA "Pas: Ghana"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-GIB "Pas: Gibraltar"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-GRC "Pas: Greece"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-GRL "Pas: Greenland"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-GRD "Pas: Grenada"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-GLP "Pas: Guadeloupe"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-GUM "Pas: Guam"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-GTM "Pas: Guatemala"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-GGY "Pas: Guernsey"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-GIN "Pas: Guinea"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-GNB "Pas: Guinea-Bissau"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-GUY "Pas: Guyana"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-HTI "Pas: Haiti"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-HMD "Pas: Heard Island and McDonald Islands"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-VAT "Pas: Holy See (the)"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-HND "Pas: Honduras"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-HKG "Pas: Hong Kong"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-HUN "Pas: Hungary"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-ISL "Pas: Iceland"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-IND "Pas: India"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-IDN "Pas: Indonesia"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-IRN "Pas: Iran (Islamic Republic of)"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-IRQ "Pas: Iraq"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-IRL "Pas: Ireland"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-IMN "Pas: Isle of Man"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-ISR "Pas: Israel"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-ITA "Pas: Italy"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-JAM "Pas: Jamaica"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-JPN "Pas: Japan"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-JEY "Pas: Jersey"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-JOR "Pas: Jordan"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-KAZ "Pas: Kazakhstan"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-KEN "Pas: Kenya"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-KIR "Pas: Kiribati"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-PRK "Pas: Korea (the Democratic People's Republic of)"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-KOR "Pas: Korea (the Republic of)"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-KWT "Pas: Kuwait"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-KGZ "Pas: Kyrgyzstan"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-LAO "Pas: Lao People's Democratic Republic (the)"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-LVA "Pas: Latvia"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-LBN "Pas: Lebanon"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-LSO "Pas: Lesotho"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-LBR "Pas: Liberia"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-LBY "Pas: Libya"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-LIE "Pas: Liechtenstein"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-LTU "Pas: Lithuania"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-LUX "Pas: Luxembourg"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-MAC "Pas: Macao"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-MDG "Pas: Madagascar"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-MWI "Pas: Malawi"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-MYS "Pas: Malaysia"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-MDV "Pas: Maldives"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-MLI "Pas: Mali"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-MLT "Pas: Malta"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-MHL "Pas: Marshall Islands (the)"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-MTQ "Pas: Martinique"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-MRT "Pas: Mauritania"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-MUS "Pas: Mauritius"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-MYT "Pas: Mayotte"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-MEX "Pas: Mexico"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-FSM "Pas: Micronesia (Federated States of)"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-MDA "Pas: Moldova (the Republic of)"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-MCO "Pas: Monaco"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-MNG "Pas: Mongolia"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-MNE "Pas: Montenegro"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-MSR "Pas: Montserrat"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-MAR "Pas: Morocco"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-MOZ "Pas: Mozambique"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-MMR "Pas: Myanmar"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-NAM "Pas: Namibia"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-NRU "Pas: Nauru"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-NPL "Pas: Nepal"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-NLD "Pas: Netherlands (Kingdom of the)"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-NCL "Pas: New Caledonia"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-NZL "Pas: New Zealand"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-NIC "Pas: Nicaragua"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-NER "Pas: Niger (the)"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-NGA "Pas: Nigeria"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-NIU "Pas: Niue"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-NFK "Pas: Norfolk Island"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-MKD "Pas: North Macedonia"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-MNP "Pas: Northern Mariana Islands (the)"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-NOR "Pas: Norway"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-OMN "Pas: Oman"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-PAK "Pas: Pakistan"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-PLW "Pas: Palau"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-PSE "Pas: Palestine, State of"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-PAN "Pas: Panama"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-PNG "Pas: Papua New Guinea"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-PRY "Pas: Paraguay"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-PER "Pas: Peru"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-PHL "Pas: Philippines (the)"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-PCN "Pas: Pitcairn"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-POL "Pas: Poland"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-PRT "Pas: Portugal"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-PRI "Pas: Puerto Rico"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-QAT "Pas: Qatar"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-ROU "Pas: Romania"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-RUS "Pas: Russian Federation (the)"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-RWA "Pas: Rwanda"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-REU "Pas: Réunion"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-BLM "Pas: Saint Barthélemy"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-SHN "Pas: Saint Helena, Ascension and Tristan da Cunha"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-KNA "Pas: Saint Kitts and Nevis"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-LCA "Pas: Saint Lucia"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-MAF "Pas: Saint Martin (French part)"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-SPM "Pas: Saint Pierre and Miquelon"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-VCT "Pas: Saint Vincent and the Grenadines"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-WSM "Pas: Samoa"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-SMR "Pas: San Marino"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-STP "Pas: Sao Tome and Principe"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-SAU "Pas: Saudi Arabia"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-SEN "Pas: Senegal"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-SRB "Pas: Serbia"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-SYC "Pas: Seychelles"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-SLE "Pas: Sierra Leone"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-SGP "Pas: Singapore"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-SXM "Pas: Sint Maarten (Dutch part)"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-SVK "Pas: Slovakia"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-SVN "Pas: Slovenia"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-SLB "Pas: Solomon Islands"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-SOM "Pas: Somalia"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-ZAF "Pas: South Africa"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-SGS "Pas: South Georgia and the South Sandwich Islands"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-SSD "Pas: South Sudan"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-ESP "Pas: Spain"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-LKA "Pas: Sri Lanka"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-SDN "Pas: Sudan (the)"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-SUR "Pas: Suriname"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-SJM "Pas: Svalbard and Jan Mayen"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-SWE "Pas: Sweden"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-CHE "Pas: Switzerland"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-SYR "Pas: Syrian Arab Republic (the)"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-TWN "Pas: Taiwan (Province of China)"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-TJK "Pas: Tajikistan"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-TZA "Pas: Tanzania, the United Republic of"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-THA "Pas: Thailand"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-TLS "Pas: Timor-Leste"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-TGO "Pas: Togo"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-TKL "Pas: Tokelau"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-TON "Pas: Tonga"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-TTO "Pas: Trinidad and Tobago"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-TUN "Pas: Tunisia"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-TKM "Pas: Turkmenistan"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-TCA "Pas: Turks and Caicos Islands (the)"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-TUV "Pas: Tuvalu"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-TUR "Pas: Türkiye"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-UGA "Pas: Uganda"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-UKR "Pas: Ukraine"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-ARE "Pas: United Arab Emirates (the)"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-GBR "Pas: United Kingdom of Great Britain and Northern Ireland (the)"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-UMI "Pas: United States Minor Outlying Islands (the)"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-USA "Pas: United States of America (the)"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-URY "Pas: Uruguay"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-UZB "Pas: Uzbekistan"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-VUT "Pas: Vanuatu"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-VEN "Pas: Venezuela (Bolivarian Republic of)"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-VNM "Pas: Viet Nam"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-VGB "Pas: Virgin Islands (British)"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-VIR "Pas: Virgin Islands (U.S.)"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-WLF "Pas: Wallis and Futuna"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-ESH "Pas: Western Sahara*"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-YEM "Pas: Yemen"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-ZMB "Pas: Zambia"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-ZWE "Pas: Zimbabwe"
* $uri#http://terminology.hl7.org/NamingSystem/opNumNS-ALA "Pas: Åland Islands"